services:
  typesense:
    image: typesense/typesense:28.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    volumes:
      - /tmp/typesense-server-data:/data
    ports:
      - "8108:8108"
    restart: 'no'
  app:
    build:
      context: ./../../oi-docker/php72-apache
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 8.17.0
    ports:
      - "80:80"
    environment:
      APACHE_DOCUMENT_ROOT: '/var/www/html'
    volumes:
      - '.:/var/www/html'